apiVersion: apps/v1
kind: Deployment
metadata:
  name: plasma-donote-app

spec:
  replicas: 5
  selector:
    matchLabels:
      app: plasma-donote-app
  template:
    metadata:
      labels:
        app: plasma-donote-app

    spec:
      containers:
        - name: plasma-donote-container
          image: jp.icr.io/plasmadonateapp/pda
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
              